on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-versions: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          envkey_OWNER: ${{secrets.OWNER}}

      - name: Install the required dependencies & build the project
        run: npm i

    build:
      steps:
        - name: Build the project using postinstall script
          run: npm run postinstall

    lint:
      steps:
        - name: test the linting errors
          run: npm run lint
    restart:
      steps:
        - name: Restart PM2
          run: pm2 start npm --name discordbot -- start
