on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
  runs-on: self-hosted

  strategy:
    - name: Install the required dependencies & build the project
      run: npm i
    - name: Build the project using postinstall script
      run: npm run postinstall
    - name: Restart PM2
      run: pm2 start npm --name discordbot -- start
